// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6B90JVBZOrKCdDOR84dOsIGUsHJeBz7I',
    appId: '1:748939819317:web:23f68351297ec79762747c',
    messagingSenderId: '748939819317',
    projectId: 'gestante-app-d51d0',
    authDomain: 'gestante-app-d51d0.firebaseapp.com',
    storageBucket: 'gestante-app-d51d0.appspot.com',
    measurementId: 'G-GWCMW3H0KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGm7yQ7P5dmDPJiw_SwuYoxABQ3addl_w',
    appId: '1:748939819317:android:7ad32a1c0b82af6262747c',
    messagingSenderId: '748939819317',
    projectId: 'gestante-app-d51d0',
    storageBucket: 'gestante-app-d51d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4dvSX0bJp7fAbIAmVDJXKRLPH5HFpTPE',
    appId: '1:748939819317:ios:144ea62e7143a01f62747c',
    messagingSenderId: '748939819317',
    projectId: 'gestante-app-d51d0',
    storageBucket: 'gestante-app-d51d0.appspot.com',
    androidClientId:
        '748939819317-0kj6ou0ku3q83rrj9j477i7ruumbjikp.apps.googleusercontent.com',
    iosClientId:
        '748939819317-svlit1g0brvgastj7rv5k5pbl0ddj20k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestApp',
  );
}
